version: "3"

services:
  db:
    image: "postgres"
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    container_name: mekari
    image: mekari:latest
    depends_on:
      - db
    links:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
volumes:
  db-data:
